### ISSUE TITLE
Any plans to publish to the PowerShell Gallery

### ISSUE THREAD

**Issue by kilasuit** [tyconsulting/AzPolicyTest#1]
In reading https://blog.tyang.org/2019/05/19/deploying-azure-policy-definitions-via-azure-devops-part-2/ - I noted that this shows using Azure Artifacts for the feed and not the PowerShell Gallery.

Do you plan to publish this to the PowerShell Gallery in future?

**Comment by tyconsulting** [comment]
it is published in PSGallery
