### ISSUE TITLE
Unable to use this module to test multiple files in policy

### ISSUE THREAD

**Issue by durgaprasad9** [tyconsulting/AzPolicyTest#4]
Hi, 

I have one azure police writen in multiple files
assignment.json
perameters.json
rule.json

The reason these files are writen in this way  is I am deploying polocies using Terraform

I am unable to test this before deploy it or attempt to create policy definition

I have bunch of polcies written in this way

**Comment by tyconsulting** [comment]
no plans to support this type of file structures
