### ISSUE TITLE
escape characters

### ISSUE THREAD

**Issue by JulianHayward** [tyconsulting/AzPolicyTest#6]
nice stuff. Quick find: when executing against the ALZ policy definitions, it moans on not parameterized effect.

example: 
https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deny-AppServiceApiApp-http.json

```
{
      "then": {
        "effect": "[[parameters('effect')]"
      }
}
```

Can you relax the regex to handle this?

ref: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-expressions#escape-characters

**Comment by tyconsulting** [comment]
thanks @JulianHayward. I have adjusted the regex to `^\[{1,2}parameters\(\'(\S+)\'\)\]$` to allow 1 or 2 `[` characters.
somehow, I only had to use the `[` character when using Windows and Linux computers, but had to remove it when using a mac. so it was overlooked :)
